---
# tasks file for jira_role

- name: JIRA | Config | Server configuration
  template:
    src: conf/server.xml.j2
    dest: "{{ jira_installation_dir }}/conf/server.xml"
    owner: "{{ jira_user }}"
    group: "{{ jira_group }}"
    mode: 0644
    backup: true
  notify: restart jira

- name: JIRA | Config | Database configuration
  template:
    src: conf/dbconfig.xml.j2
    dest: "{{ jira_home }}/dbconfig.xml"
    owner: "{{ jira_user }}"
    group: "{{ jira_group }}"
    mode: 0644
    backup: true
  when: jira_database_configuration
  notify: restart jira

- name: JIRA | Config | Environmnent configuration
  template:
    src: bin/setenv.sh.j2
    dest: "{{ jira_installation_dir }}/bin/setenv.sh"
    owner: "{{ jira_user }}"
    group: "{{ jira_group }}"
    mode: 0755
    backup: true
  notify: restart jira

- name: JIRA | Config | Creating service from template
  template:
    src: init.d/jira.service.j2
    dest: "{{ jira_service }}"
    owner: "{{ jira_user }}"
    group: "{{ jira_group }}"
    mode: 0644
  notify: restart jira

- name: JIRA | Config | Configuring service
  systemd:
    name: "{{ jira_service_name }}"
    state: "{{ jira_service_state }}"
    enabled: "{{ jira_service_enabled }}"
    daemon_reload: true

- name: JIRA | Config | Copying extra files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "{{ jira_user }}"
    group: "{{ jira_group }}"
  notify: restart jira
  with_items: "{{ jira_extra_copy_files }}"
  when: jira_extra_copy_files is defined

- name: JIRA | Config | Copying template extra files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "{{ jira_user }}"
    group: "{{ jira_group }}"
  notify: restart jira
  with_items: "{{ jira_extra_template_files }}"
  when: jira_extra_template_files is defined
