---
# tasks file for jira_role

- name: JIRA | DataCenter | Master | Create cluster properties
  template:
    src: cluster.properties.j2
    dest: "{{ jira_home }}"
    owner: "{{ jira_user }}"
    group: "{{ jira_group }}"
    mode: 0644
  notify: restart jira
