---
# tasks file for jira_role

- name: JIRA | DataCenter | Create cluster properties
  template:
    src: cluster.properties.j2
    dest: "{{ jira_home }}"
    owner: "{{ jira_user }}"
    group: "{{ jira_group }}"
    mode: 0644
  notify: restart jira

- name: JIRA | DataCenter | Install NFS common
  apt:
    name: nfs-common
    state: present
    autoclean: true
    autoremove: true
    install_recommends: true

- name: JIRA | DataCenter | Create folder for shared home
  file:
    path: "{{ jira_datacenter_shared }}"
    state: directory
    owner: jira
    group: jira
    mode: 0755

- name: JIRA | DataCenter | Mount shared folder
  mount:
    backup: true
    path: "{{ jira_datacenter_shared }}"
    src: "{{ jira_datacenter_mountpoint }}"
    state: mounted
    opts: "{{ jira_datacenter_mountopts }}"
    fstype: nfs
